Este bloque de código importa la librería pandas.

In [ ]:
import pandas as pd

Este bloque de código crea un diccionario llamado data con información sobre nombres, edades y género.

In [ ]:
data = {"name": ["Sally", "Jhon", "Kim"], "age": [4, 6 ,7], "gender": ["female", "male", "male"]}

Este bloque de código convierte el diccionario data en un DataFrame.

In [ ]:
pd.DataFrame(data)

    name  age  gender
0  Sally    4  female
1   Jhon    6    male
2    Kim    7    male

Este bloque de código crea un DataFrame asignando índices personalizados a cada fila.

In [ ]:
pd.DataFrame(data, index = ["Kid1", "Kid2", "Kid3"])

       name  age  gender
Kid1  Sally    4  female
Kid2   Jhon    6    male
Kid3    Kim    7    male